In [1]:
from mxnet import ndarray as nd

In [2]:
# 然后我们创建一个3行和4列的2D数组（通常也叫矩阵），并且把每个元素初始化成0
nd.zeros((3, 4))


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

In [3]:
#我们可以创建数组每个元素被初始化成1
x = nd.ones((3, 4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [4]:
#从python的数组直接构造
nd.array([[1,2],[2,3]])


[[ 1.  2.]
 [ 2.  3.]]
<NDArray 2x2 @cpu(0)>

In [5]:
#创建数组，它的元素服从均值0标准差1的正态分布
y = nd.random_normal(0, 1, shape=(3, 4))
y


[[ 2.21220636  0.7740038   1.04344046  1.18392551]
 [ 1.89171135 -1.23474145 -1.771029   -0.45138445]
 [ 0.57938355 -1.85608196 -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [6]:
#跟NumPy一样，每个数组的形状可以通过.shape来获取
y.shape

(3, 4)

In [7]:
#总元素个数，是形状的累乘
y.size

12

## 操作符

In [8]:
#NDArray支持大量的数学操作符，例如按元素加法：
x+y


[[ 3.21220636  1.77400374  2.04344034  2.18392563]
 [ 2.89171124 -0.23474145 -0.771029    0.54861557]
 [ 1.57938361 -0.85608196 -0.9768796   0.7919808 ]]
<NDArray 3x4 @cpu(0)>

In [9]:
#乘法
x * y


[[ 2.21220636  0.7740038   1.04344046  1.18392551]
 [ 1.89171135 -1.23474145 -1.771029   -0.45138445]
 [ 0.57938355 -1.85608196 -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [10]:
#指数运算：
nd.exp(y)


[[ 9.13585091  2.16843081  2.83896756  3.26717448]
 [ 6.63070631  0.29090998  0.17015781  0.63674599]
 [ 1.78493774  0.15628375  0.13850074  0.81219143]]
<NDArray 3x4 @cpu(0)>

In [11]:
#也可以转置一个矩阵然后计算矩阵乘法：
nd.dot(x, y.T)


[[ 5.21357632 -1.56544352 -3.4615972 ]
 [ 5.21357632 -1.56544352 -3.4615972 ]
 [ 5.21357632 -1.56544352 -3.4615972 ]]
<NDArray 3x3 @cpu(0)>

### 广播（Broadcasting）

In [12]:
a = nd.arange(3).reshape((3,1))
b = nd.arange(2).reshape((1,2))
print('a:', a)
print('b:', b)
print('a+b:', a+b)


a: 
[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>
b: 
[[ 0.  1.]]
<NDArray 1x2 @cpu(0)>
a+b: 
[[ 0.  1.]
 [ 1.  2.]
 [ 2.  3.]]
<NDArray 3x2 @cpu(0)>


### 跟NumPy的转换

In [13]:
import numpy as np
x = np.ones((2,3))
y = nd.array(x)  # numpy -> mxnet
z = y.asnumpy()  # mxnet -> numpy
print([z, y])

[array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32), 
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>]


### 截取（Slicing）

In [14]:
#NXNet NDArray 提供了各种截取方法。截取 x 的 index 为 1、2 的列：
x = nd.arange(0,9).reshape((3,3))
print('x: ', x)
x[1:3]

x:  
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>



[[ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 2x3 @cpu(0)>

In [15]:
#直接写入指定位置：
x[1,2] = 9.0
x


[[ 0.  1.  2.]
 [ 3.  4.  9.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>

In [16]:
#多维截取：
x = nd.arange(0,9).reshape((3,3))
print('x: ', x)
x[1:2,1:3]

x:  
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>



[[ 4.  5.]]
<NDArray 1x2 @cpu(0)>

In [17]:
#多维写入：
x[1:2,1:3] = 9.0
x


[[ 0.  1.  2.]
 [ 3.  9.  9.]
 [ 6.  7.  8.]]
<NDArray 3x3 @cpu(0)>